### ISSUE TITLE
Unable to both download Drush command and copy site aliases

### ISSUE THREAD

**Issue by fluxsauce** [aquifer/aquifer#103]
Given the following

``` yml
libraries:
  registry_rebuild:
    destination: "drush"
    download:
      type: "file"
      url: "http://ftp.drupal.org/files/projects/registry_rebuild-7.x-2.2.tar.gz"
```

and a `drush` directory that contains aliases / `drushrc` configurations, you get a conflict.

![screen shot 2016-01-05 at 3 26 04 pm](https://cloud.githubusercontent.com/assets/976391/12130630/aec53b68-b3c0-11e5-8e89-4c5b2725bca5.png)

Expected behavior: contents merge.
